# netlify.toml (i prosjektroten)

[build]
  command = "npm run build"
  publish = "dist"          # Vite output

# --- Ikke la deploy previews og branch deploys indekseres ---
[context.deploy-preview.headers]
  for = "/*"
  [context.deploy-preview.headers.values]
    X-Robots-Tag = "noindex, nofollow"

[context.branch-deploy.headers]
  for = "/*"
  [context.branch-deploy.headers.values]
    X-Robots-Tag = "noindex, nofollow"

# --- (Valgfritt) Redirects; bruk dette hvis du vil mappe gamle stier ---
# [[redirects]]
#   from = "/gammel-sti/*"
#   to = "/ny-sti/:splat"
#   status = 301
#   force = true

# --- (Valgfritt) Caching for statiske assets ---
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# --- (Valgfritt) Sikkerhetsheaders ---
[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "0"
